FROM python:3.12-slim

WORKDIR /app

COPY app*.py .
COPY requirements.txt .

RUN pip install -r requirements.txt

EXPOSE 5000

# --app app_test is the root file specified
CMD flask --app app_test run --host=0.0.0.0 --port=5000